# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm <- function(mean, Precision) {
    .Call(`_ModBart_rmvnorm`, mean, Precision)
}

rmvnorm_eig <- function(mean, Precision) {
    .Call(`_ModBart_rmvnorm_eig`, mean, Precision)
}

rlgam <- function(shape) {
    .Call(`_ModBart_rlgam`, shape)
}

rcpparma_hello_world <- function() {
    .Call(`_ModBart_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ModBart_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ModBart_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ModBart_rcpparma_bothproducts`, x)
}

update_b <- function(Z, b_new, mu_new, b_old, mu_old, cluster_idx, sigma) {
    .Call(`_ModBart_update_b`, Z, b_new, mu_new, b_old, mu_old, cluster_idx, sigma)
}

